username: ENC[AES256_GCM,data:zB/h1LXX0L4=,iv:zJSaec7SVUWHvHBsEUpAILyLotlfogZ0UE78KZRHiuU=,tag:GFxRhVfYDwEz7iUCLbjQXw==,type:str]
password: ENC[AES256_GCM,data:5KlBPxaY57g=,iv:fYr2Y5PXyB4OtNQTK0WvkWB1TJ4ZIsPEVXk4rdkSOHA=,tag:kdb60FtMKq1BeeVp5Twjeg==,type:str]
database: ENC[AES256_GCM,data:kA4LyqZrQNROGQ==,iv:zQ6zdn7AQ061FFkjd45VemGRt/smbKRLXSx7Ekwfhuo=,tag:zmcqMnoAMxhBGReGNDNMTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-17T17:00:03Z"
    mac: ENC[AES256_GCM,data:0hDBEx7NyrBvySCayiHJWGanDpKvQqwhe8K2EHCQK01n2BYNd5+czLX0EDBMWUi6wAPzqA9CXcnqdwD0C5G3Gvahb1hvo/+Cycc5ZUs5cx5b7g5vXkHQN6AV/ihmJ8HiO6yg2Tqw3AvQC0ILP4DGKTZtqAsWkho/R/Te8LVYRhQ=,iv:Ovc43pU8ag4EyuyKWI5KP+FU9aByKxtcaXYSK/IAVE8=,tag:22+bP0r1zRqkVpa1PUQ1qg==,type:str]
    pgp:
        - created_at: "2023-03-17T16:59:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA1+U5l5Yuk/bAQwAr3xUNr9h+by2kQba9TlPcTFNdQDsm7TqSqnC+TimADeu
            nqKL3fhdrdWLWl9v04b0XFlOdrqXOY+uAxsfn+/tEXPb3buTgOJXS8AXUg0NApeV
            sOilGACsokF8USoRKTN5WB2adF3Yv71Ys49XV/KB0Nr9+6Ug+lidSMZlut8eFThL
            kGVU8lz40om1b/lGYx88jxHED7WG79PfTmHin6HO0poNL+V+DT/mRc9a5peepEEV
            TwpQltRdQdiXaX2YR77tjZpPUayoWaVMymVp8MD07ZtaCDXEEiXhiRCfu9OV/6xX
            hQQNgQRC5JYpF4DG+6tRpHo/r2UCu5jhRvT9cSk4ctG3xKIwTiIoERl7CNSteU8Q
            AAL1RYXIv877sJHPM8BuhZg6WADLjCR3slAciTwgpdAJCm0MgKIBNju0n60/wr5C
            JZG6N09ELZhMtJVwt6ToA+PYueSqyUBGvgMpNjC4OD3HxI5IpHA4iQ+2u8FBBiy7
            ZiUkWjeJh8OSNWtGz4ES1GgBCQIQs+pQ3pYz0vBR+kvoodg9hQPlAaYQqPGWT9Uc
            LrErrwQ8sXoWBoIIb8QKOo5FX+hwsZN9Y8eApOSCezcJBiCIiEZmgtkpv85cH5Ap
            5upf0GadEnRWWboSOc868emt+J03D8upDw==
            =43lR
            -----END PGP MESSAGE-----
          fp: 9F2F354A1F049A1D9C751A98C34A38C0A0546F15
    unencrypted_suffix: _unencrypted
    version: 3.7.3
