apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero2prod-deployment
  labels:
    app: zero2prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zero2prod
  template:
    metadata:
      labels:
        app: zero2prod
    spec:
      containers:
        - name: zero2prod
          image: "ghcr.io/nambrosini/zero2prod:{{ .Chart.Version }}"
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health_check
              port: 8000
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: /health_check
              port: 8000
