apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero2prod-deployment
  labels:
    app: zero2prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zero2prod
  template:
    metadata:
      labels:
        app: zero2prod
    spec:
      containers:
        - name: zero2prod
          image: "docker.io/nambrosini/zero2prod:{{ default .Chart.Version .Values.imageVersion }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.containerPort }}
          readinessProbe:
            httpGet:
              path: /health_check
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: /health_check
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 30
